[project]
name = "intro-acp-beeai"
version = "0.1.0"
description = "An introduction to ACP and the BeeAI Platform using a ticket triage scenario."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "acp-sdk>=0.10.1",
    "beeai-framework>=0.1.23",
    "pydantic-ai>=0.2.14",
]
