[project]
name = "beeai-workshop"
version = "0.1.0"
description = "BeeAI workshop"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "acp-sdk==0.10.1",
    "beeai-framework==0.1.23",
    "pydantic-ai==0.2.14",
]

[tool.uv.workspace]
members = [
    "src/intro_acp_beeai",
]
