name: Build website

on:
  pull_request:
    branches:
      - main
    paths:
      - 'data/**'
      - 'docs/**'
      - 'notebooks/**'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python 3.12'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 'Create venv'
        run: |
          python3 -m venv --upgrade-deps venv

      - name: 'Install mkdocs'
        run: |
          source venv/bin/activate
          python3 -m pip install 'mkdocs-material[imaging]'

      - name: 'Build website'
        run: |
          source venv/bin/activate
          mkdocs build --strict
