name: Publish website

on:
  push:
    branches:
      - main

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python 3.12'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 'Create venv'
        run: |
          python3 -m venv --upgrade-deps venv

      - name: 'Install mkdocs'
        run: |
          source venv/bin/activate
          python3 -m pip install 'mkdocs-material[imaging]'

      - name: 'Publish website'
        run: |
          source venv/bin/activate
          mkdocs gh-deploy --force
